version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: match_simulation_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: match_simulation
      DB_USERNAME: match_simulation
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: match_simulation_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: match_simulation_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: match_simulation
      MYSQL_USER: match_simulation
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: match_simulation_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: match_simulation_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: match_simulation
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:
  redis_data:
  vendor:

networks:
  app-network:
    driver: bridge